

print('''
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

Answer: 4613732\n''')

print('Method 1: Computational Brute Force')

def fibncc(i):
    if i==1: return 1
    if i==2: return 2
    return fibncc(i-1)+fibncc(i-2)

i = 2; ans = 0
while True:
    f = fibncc(i)
    if f>4000000: break
    ans += f
    i += 3

print(ans, '\n')


print('Method 2: Computational Brute Force with Mathematical Simplification')

fibncc2 = [2, 8]
# fibncc2(n) = 4 * fibncc2(n-1) + fibncc2(n-2)

n = 2; ans = 2+8
while True:
    f = 4 * fibncc2[n-1] + fibncc2[n-2]
    if f>4000000: break
    fibncc2.append(f)
    ans += f
    n += 1

print(ans, '\n')

